# Generated by Django 3.2.5 on 2022-05-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
